name: Bandit

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@v1
        with:
            exclude: "integration_tests/*,unit_tests/*"