name: ZAP Baseline DAST Scan

on:
  push:
    branches:
      - main    # <-- uniquement sur la branche principale (default branch)

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and run app in Docker
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/myapp:dev-${{ github.sha }} .
          docker run -d -it -p 8080:8080 ${{ vars.DOCKERHUB_USERNAME }}/myapp:dev-${{ github.sha }} 
          sleep 10   

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
            target: 'http://localhost:8080'
            fail_action: false
  
      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
            name: zap-report
            path: |
              zap_report.json
