name: Docker

on: []

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/myapp:dev-${{ github.sha }} .

      - name: Push image to Docker Hub
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/myapp:dev-${{ github.sha }}

  scan-container:
    name: Scan Container Image with Trivy
    runs-on: ubuntu-latest
    needs: docker  
    continue-on-error: true 
        
    steps:
      - uses: actions/checkout@v4
        
      - name: Install Trivy
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/myapp:dev-${{ github.sha }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          continue-on-error: true
      

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
    
  sbom:
    name: Generate SBOM with Syft
    runs-on: ubuntu-latest
    needs: docker

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Generate SBOM from project directory
          uses: anchore/sbom-action@v0
          with:
            source: dir:.
            format: syft-json
            output-file: sbom.syft.json


        - name: Upload SBOM files
          uses: actions/upload-artifact@v4
          with:
            name: sbom-files
            path: |
              sbom.syft.json
              sbom.cyclonedx.json
            retention-days: 90
  
  sbom-scan:
    name: Scan SBOM with Grype
    runs-on: ubuntu-latest
    needs: sbom

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download SBOM artifact
        uses: actions/download-artifact@v4
        with:
          name: sbom-files
          path: ./sbom

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Grype scan on SBOM
        run: |
          grype sbom:./sbom/sbom.syft.json -o table > grype-report.txt
          grype sbom:./sbom/sbom.syft.json -o sarif > grype-report.sarif

      - name: Upload Grype report
        uses: actions/upload-artifact@v4
        with:
          name: grype-reports
          path: |
            grype-report.txt
            grype-report.sarif
          retention-days: 90

      - name: Upload to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: grype-report.sarif

        
        


