name: Docker

on: [push, pull_request]

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: |
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/myapp:dev-${{ github.sha }} .

      - name: Push image to Docker Hub
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/myapp:dev-${{ github.sha }}

  scan-container:
    name: Scan Container Image with Trivy
    runs-on: ubuntu-latest
    needs: docker  
    continue-on-error: true 
        
    steps:
      - uses: actions/checkout@v4
        
      - name: Install Trivy
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/mon-app:dev-${{ github.sha }}
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          format: 'table'
          exit-code: '0'  # ne fait pas échouer le job
      

      - name: Log in to Docker Hub (required to pull image)
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin
        
      - name: Scan image with Trivy (only HIGH and CRITICAL)
        run: |
          IMAGE=${{ vars.DOCKERHUB_USERNAME }}/mon-app:dev-${{ github.sha }}
          trivy image --severity HIGH,CRITICAL --no-progress $IMAGE
        
        


